### ISSUE TITLE
metal on layer 5

### ISSUE THREAD

**Issue by mattvenn** [MikeCovrado/z2a_project#2]
Hi Mike, 
you're probably aware but you have metal on layer 5 which isn't allowed for a non-core macro. See page 5 of project 4.2 regarding config adjustments to correct this.

**Comment by MikeCovrado** [comment]
AAhhhhh.  _Good catch_!   I was aware of this, but in the rush to get everything together, I did forget.   Thanks for the save.   I'll re-generated and close this issue when it available.

**Comment by MikeCovrado** [comment]
Fixed as of 73fdc59.
